repos:
    -   repo: https://github.com/psf/black
        rev: 20.8b1
        hooks:
        - id: black
          language_version: python3.6
        # Refer https://github.com/pre-commit/pre-commit/issues/1206#issuecomment-551000892
    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.8.3
        hooks:
        - id: flake8